services:
  db:
    image: mysql:9.0.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: osint_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping"]
      interval: 10s
      timeout: 2s
      retries: 10
    networks:
      - osint-network

  backend:
    build:
      context: osintapp
      dockerfile: ./prod.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - osint-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  frontend:
    build:
      context: ./osint-client
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - osint-network

networks:
  osint-network:
    driver: bridge