services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: osint_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping" ]
      interval: 10s
      timeout: 2s
      retries: 10
    network_mode: host

  backend:
    build:
      context: osintapp
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    network_mode: host